var baseURL = '../../';
var commURL = '../../../common/';
var include = {
	meta : function(){
		document.write('<meta http-equiv="X-UA-Compatible" content="IE=edge">');
		document.write('<meta name="viewport" content="width=device-width,maximum-scale=1,minimum-scale=1,user-scalable=no">');
		//document.write('<meta name="format-detection" content="telephone=no">');
	},
	styles : function(){
		document.write('<link rel="stylesheet" href="'+baseURL+'css/common_m.css" type="text/css" />');
		document.write('<link rel="stylesheet" href="'+baseURL+'css/content_m.css" type="text/css" />');
	},
	scripts : function(){
		document.write('<script src="'+commURL+'js/lib/jquery-3.5.1.min.js"></script>');
		document.write('<script src="'+commURL+'js/lib/swiper.js"></script>');
		document.write('<script src="'+commURL+'js/lib/jquery-ui.min.js"></script>');
		document.write('<script src="'+baseURL+'js/pub/content_m_ui.js"></script>');
	},
	title : function(){
		document.write('<title>랭킹닭컴</title>');
	},
	skipNav : function(){
		document.write('<div class="skip-navi"><a href="#gnb">주요 메뉴 바로가기</a><a href="#contents">본문 컨텐츠 바로가기</a></div>');
	},
	header : function(){
		document.write('<div class="header-top">');
		document.write('<div class="header-inner">');
		document.write('<h1 class="logo">');
		document.write('<a href="#"><i class="head-logo"></i><span class="blind">랭킹닭컴</span></a>');
		document.write('</h1>');
		document.write('<div class="header-search">');
		document.write('<div class="top-search">');
		document.write('<input type="search" class="input-search" value="국민간식 단백천하 소시지" />');
		document.write('<button type="button" class="btn-top-search" title="검색"><span class="blind">검색</span></button>');
		document.write('</div>');
		document.write('</div>');
		document.write('<!--// header-search -->');
		document.write('<div class="my-menu">');
		document.write('<ul>');
		document.write('<li><a href="#" class="btn-util-cart" title="장바구니"><span class="blind">장바구니</span><em class="count">1</em></a></li>');
		document.write('</ul>');
		document.write('</div><!--// my-menu -->');
		document.write('</div><!--// header-inner -->');
		document.write('</div><!--// header-top -->');
		document.write('<div class="gnb-wrap">');
		document.write('<div class="inner">');
		document.write('<nav id="gnb" class="gnb">');
		document.write('<ul>');
		document.write('<li><a href="#"><span>랭킹</span></a></li>');
		document.write('<li><a href="#"><span>이달의 특가</span></a></li>');
		document.write('<li><a href="#"><span>혜택정리</span></a></li>');
		document.write('<li><a href="#"><span>종류별</span></a></li>');
		document.write('<li><a href="#"><em class="ico-txt-gnb"><span class="blind">특급배송</span></em></a></li>');
		document.write('</ul>');
		document.write('</nav><!--// gnb -->');
		document.write('</div><!--// inner -->');
		document.write('</div><!--// gnb-wrap -->');
	},
	lnb : function(){
		document.write('<div class="lnb-wrap" id="lnb">');
		document.write('<div class="lnb-inner">');
		document.write('<div class="lnb-head">');
		document.write('<div class="inner">');
		document.write('<span class="user-level">닭차장</span>');
		document.write('<p class="user-name"><em>kyoung111111</em>님 <i class="ico-arr-right"></i></p>');
		document.write('<a href="#" class="btn-util-cart2" title="장바구니"><span class="blind">장바구니</span><em class="count">1</em></a>');
		document.write('</div><!--// inner -->');
		document.write('</div><!--// lnb-head -->');
		document.write('<div class="lnb-body">');
		document.write('<div class="lnb-menu-box">');
		document.write('<ul class="inner-flex">');
		document.write('<li class="grow-item3"><a href="#"><i class="ico-lnbbox-gift"></i><span class="txt">선물하기</span></a></li>');
		document.write('<li class="grow-item3"><a href="#"><i class="ico-lnbbox-exp"></i><span class="txt">특급배송</span></a></li>');
		document.write('<li class="grow-item3"><a href="#"><i class="ico-lnbbox-event"></i><span class="txt">이벤트</span></a></li>');
		document.write('</ul>');
		document.write('</div><!--// lnb-menu-box -->');
		document.write('<nav class="nav-area">');
		document.write('<ul class="nav-list">');
		document.write('<li><a href="#"><i class="ico-cate-new"></i><span class="txt">신상품</span><i class="ico-arr-right"></i></a></li><!-- 활성화시 li addClass current -->');
		document.write('<li><a href="#"><i class="ico-cate-onepack"></i><span class="txt">한팩담기</span><i class="ico-arr-right"></i></a></li>');
		document.write('<li>');
		document.write('<a href="#"><i class="ico-cate-chicken"></i><span class="txt">닭가슴살</span><i class="ico-arr-toggle"></i></a>');
		document.write('<ul class="depth2">');
		document.write('<li><a href="#"><span>전체</span></a></li>');
		document.write('<li><a href="#"><span>스테이크</span></a></li>');
		document.write('<li><a href="#"><span>스팀&middot;소프트</span></a></li>');
		document.write('<li><a href="#"><span>볼&middot;큐브</span></a></li>');
		document.write('<li><a href="#"><span>슬라이스</span></a></li>');
		document.write('<li><a href="#"><span>훈제</span></a></li>');
		document.write('<li><a href="#"><span>프로틴</span></a></li>');
		document.write('<li><a href="#"><span>저염&middot;염분무첨가</span></a></li>');
		document.write('<li><a href="#"><span>소시지&middot;햄</span></a></li>');
		document.write('<li><a href="#"><span>소스닭가슴살</span></a></li>');
		document.write('<li><a href="#"><span>생&middot;다짐육</span></a></li>');
		document.write('<li><a href="#"><span>육포</span></a></li>');
		document.write('<li><a href="#"><span>실온 보관</span></a></li>');
		document.write('<li><a href="#"><span>스낵&middot;칩</span></a></li>');
		document.write('<li><a href="#"><span>삼계탕</span></a></li>');
		document.write('</ul>');
		document.write('</li>');
		document.write('<li>');
		document.write('<a href="#"><i class="ico-cate-instant"></i><span class="txt">즉석 간편식</span><i class="ico-arr-toggle"></i></a>');
		document.write('<ul class="depth2">');
		document.write('<li><a href="#"><span>전체</span></a></li>');
		document.write('<li><a href="#"><span>즉석밥</span></a></li>');
		document.write('<li><a href="#"><span>핫도그</span></a></li>');
		document.write('<li><a href="#"><span>브리또</span></a></li>');
		document.write('<li><a href="#"><span>만두</span></a></li>');
		document.write('<li><a href="#"><span>삼계탕</span></a></li>');
		document.write('<li><a href="#"><span>카레&middot;짜장</span></a></li>');
		document.write('<li><a href="#"><span>라면&middot;쌀국수</span></a></li>');
		document.write('<li><a href="#"><span>곤약면&middot;파스타</span></a></li>');
		document.write('<li><a href="#"><span>떡볶이&middot;튀김&middot;순대</span></a></li>');
		document.write('<li><a href="#"><span>치킨</span></a></li>');
		document.write('<li><a href="#"><span>피자&middot;탕수육</span></a></li>');
		document.write('<li><a href="#"><span>떡</span></a></li>');
		document.write('</ul>');
		document.write('</li>');
		document.write('<li>');
		document.write('<a href="#"><i class="ico-cate-lunchbox"></i><span class="txt">도시락&middot;볶음밥</span><i class="ico-arr-toggle"></i></a>');
		document.write('<ul class="depth2">');
		document.write('<li><a href="#"><span>전체</span></a></li>');
		document.write('<li><a href="#"><span>다이어트 도시락</span></a></li>');
		document.write('<li><a href="#"><span>더담은 도시락</span></a></li>');
		document.write('<li><a href="#"><span>간편 도시락</span></a></li>');
		document.write('<li><a href="#"><span>볶음밥</span></a></li>');
		document.write('<li><a href="#"><span>덮밥&middot;컵밥</span></a></li>');
		document.write('<li><a href="#"><span>간편 죽</span></a></li>');
		document.write('</ul>');
		document.write('</li>');
		document.write('<li>');
		document.write('<a href="#"><i class="ico-cate-meat"></i><span class="txt">소&middot;돼지&middot;닭안심</span><i class="ico-arr-toggle"></i></a>');
		document.write('<ul class="depth2">');
		document.write('<li><a href="#"><span>전체</span></a></li>');
		document.write('<li><a href="#"><span>소고기</span></a></li>');
		document.write('<li><a href="#"><span>돼지고기</span></a></li>');
		document.write('<li><a href="#"><span>닭 안심</span></a></li>');
		document.write('<li><a href="#"><span>오리고기</span></a></li>');
		document.write('</ul>');
		document.write('</li>');
		document.write('<li>');
		document.write('<a href="#"><i class="ico-cate-bread"></i><span class="txt">빵&middot;시리얼&middot;간식</span><i class="ico-arr-toggle"></i></a>');
		document.write('<ul class="depth2">');
		document.write('<li><a href="#"><span>전체</span></a></li>');
		document.write('<li><a href="#"><span>베이커리</span></a></li>');
		document.write('<li><a href="#"><span>햄버거</span></a></li>');
		document.write('<li><a href="#"><span>과자&middot;쿠키</span></a></li>');
		document.write('<li><a href="#"><span>프로틴 스낵</span></a></li>');
		document.write('<li><a href="#"><span>시리얼&middot;바</span></a></li>');
		document.write('<li><a href="#"><span>초콜릿</span></a></li>');
		document.write('<li><a href="#"><span>젤리</span></a></li>');
		document.write('<li><a href="#"><span>아이스크림</span></a></li>');
		document.write('<li><a href="#"><span>치즈&middot;잼</span></a></li>');
		document.write('</ul>');
		document.write('</li>');
		document.write('<li>');
		document.write('<a href="#"><i class="ico-cate-salad"></i><span class="txt">샐러드&middot;과일</span><i class="ico-arr-toggle"></i></a>');
		document.write('<ul class="depth2">');
		document.write('<li><a href="#"><span>전체</span></a></li>');
		document.write('<li><a href="#"><span>알뜰샐러드</span></a></li>');
		document.write('<li><a href="#"><span>토핑샐러드</span></a></li>');
		document.write('<li><a href="#"><span>과일</span></a></li>');
		document.write('<li><a href="#"><span>샐러드 소스</span></a></li>');
		document.write('</ul>');
		document.write('</li>');
		document.write('<li>');
		document.write('<a href="#"><i class="ico-cate-beverage"></i><span class="txt">음료&middot;프로틴</span><i class="ico-arr-toggle"></i></a>');
		document.write('<ul class="depth2">');
		document.write('<li><a href="#"><span>전체</span></a></li>');
		document.write('<li><a href="#"><span>우유&middot;두유</span></a></li>');
		document.write('<li><a href="#"><span>물&middot;탄산수</span></a></li>');
		document.write('<li><a href="#"><span>과일&middot;건강즙</span></a></li>');
		document.write('<li><a href="#"><span>프로틴 음료</span></a></li>');
		document.write('<li><a href="#"><span>프로틴 쉐이크</span></a></li>');
		document.write('<li><a href="#"><span>커피&middot;차</span></a></li>');
		document.write('<li><a href="#"><span>클렌즈&middot;주스</span></a></li>');
		document.write('</ul>');
		document.write('</li>');
		document.write('<li>');
		document.write('<a href="#"><i class="ico-cate-egg"></i><span class="txt">달걀&middot;난백&middot;콩</span><i class="ico-arr-toggle"></i></a>');
		document.write('<ul class="depth2">');
		document.write('<li><a href="#"><span>전체</span></a></li>');
		document.write('<li><a href="#"><span>구운&middot;훈제란</span></a></li>');
		document.write('<li><a href="#"><span>반숙란</span></a></li>');
		document.write('<li><a href="#"><span>난백&middot;흰자</span></a></li>');
		document.write('<li><a href="#"><span>비건&middot;콩</span></a></li>');
		document.write('</ul>');
		document.write('</li>');
		document.write('<li>');
		document.write('<a href="#"><i class="ico-cate-nuts"></i><span class="txt">견과&middot;고구마&middot;감자</span><i class="ico-arr-toggle"></i></a>');
		document.write('<ul class="depth2">');
		document.write('<li><a href="#"><span>전체</span></a></li>');
		document.write('<li><a href="#"><span>견과&middot;잡곡</span></a></li>');
		document.write('<li><a href="#"><span>고구마</span></a></li>');
		document.write('<li><a href="#"><span>감자</span></a></li>');
		document.write('<li><a href="#"><span>호박</span></a></li>');
		document.write('<li><a href="#"><span>밤</span></a></li>');
		document.write('</ul>');
		document.write('</li>');
		document.write('<li>');
		document.write('<a href="#"><i class="ico-cate-sidedish"></i><span class="txt">반찬&middot;밀키트&middot;안주</span><i class="ico-arr-toggle"></i></a>');
		document.write('<ul class="depth2">');
		document.write('<li><a href="#"><span>전체</span></a></li>');
		document.write('<li><a href="#"><span>밀키트</span></a></li>');
		document.write('<li><a href="#"><span>햄&middot;소시지</span></a></li>');
		document.write('<li><a href="#"><span>잡채&middot;동그랑땡</span></a></li>');
		document.write('<li><a href="#"><span>건강반찬</span></a></li>');
		document.write('<li><a href="#"><span>국&middot;탕&middot;찌개</span></a></li>');
		document.write('<li><a href="#"><span>참치</span></a></li>');
		document.write('<li><a href="#"><span>건강 안주</span></a></li>');
		document.write('<li><a href="#"><span>곱창&middot;껍데기</span></a></li>');
		document.write('</ul>');
		document.write('</li>');
		document.write('<li>');
		document.write('<a href="#"><i class="ico-cate-health"></i><span class="txt">건강식품</span><i class="ico-arr-toggle"></i></a>');
		document.write('<ul class="depth2">');
		document.write('<li><a href="#"><span>전체</span></a></li>');
		document.write('<li><a href="#"><span>영양제&middot;비타민</span></a></li>');
		document.write('<li><a href="#"><span>흑마늘&middot;꿀&middot;홍삼</span></a></li>');
		document.write('<li><a href="#"><span>다이어트 보조제</span></a></li>');
		document.write('<li><a href="#"><span>콜라겐</span></a></li>');
		document.write('</ul>');
		document.write('</li>');
		document.write('<li>');
		document.write('<a href="#"><i class="ico-cate-seafood"></i><span class="txt">수산&middot;해산</span><i class="ico-arr-toggle"></i></a>');
		document.write('<ul class="depth2">');
		document.write('<li><a href="#"><span>전체</span></a></li>');
		document.write('<li><a href="#"><span>생선구이</span></a></li>');
		document.write('<li><a href="#"><span>연어&middot;참치</span></a></li>');
		document.write('<li><a href="#"><span>오징어</span></a></li>');
		document.write('<li><a href="#"><span>어묵&middot;스테이크</span></a></li>');
		document.write('<li><a href="#"><span>다시마&middot;해조류</span></a></li>');
		document.write('<li><a href="#"><span>황태포&middot;쥐포</span></a></li>');
		document.write('</ul>');
		document.write('</li>');
		document.write('<li>');
		document.write('<a href="#"><i class="ico-cate-sauce"></i><span class="txt">소스&middot;잼&middot;오일</span><i class="ico-arr-toggle"></i></a>');
		document.write('<ul class="depth2">');
		document.write('<li><a href="#"><span>전체</span></a></li>');
		document.write('<li><a href="#"><span>소스&middot;드레싱</span></a></li>');
		document.write('<li><a href="#"><span>과일청</span></a></li>');
		document.write('<li><a href="#"><span>잼</span></a></li>');
		document.write('<li><a href="#"><span>오일</span></a></li>');
		document.write('<li><a href="#"><span>분말&middot;시즈닝</span></a></li>');
		document.write('</ul>');
		document.write('</li>');
		document.write('<li>');
		document.write('<a href="#"><i class="ico-cate-diet"></i><span class="txt">식단&middot;맛보기</span><i class="ico-arr-toggle"></i></a>');
		document.write('<ul class="depth2">');
		document.write('<li><a href="#"><span>전체</span></a></li>');
		document.write('<li><a href="#"><span>식단</span></a></li>');
		document.write('<li><a href="#"><span>맛보기</span></a></li>');
		document.write('<li><a href="#"><span>선물세트</span></a></li>');
		document.write('</ul>');
		document.write('</li>');
		document.write('<li>');
		document.write('<a href="#"><i class="ico-cate-exer"></i><span class="txt">운동용품</span><i class="ico-arr-toggle"></i></a>');
		document.write('<ul class="depth2">');
		document.write('<li><a href="#"><span>전체</span></a></li>');
		document.write('<li><a href="#"><span>스트랩&middot;장갑</span></a></li>');
		document.write('<li><a href="#"><span>보호대&middot;밴드</span></a></li>');
		document.write('<li><a href="#"><span>보틀&middot;쉐이커</span></a></li>');
		document.write('<li><a href="#"><span>홈트레이닝</span></a></li>');
		document.write('<li><a href="#"><span>스포츠웨어</span></a></li>');
		document.write('<li><a href="#"><span>굿즈</span></a></li>');
		document.write('</ul>');
		document.write('</li>');
		document.write('</ul><!--// nav-list -->');
		document.write('</nav><!--// nav-area -->');
		document.write('');
		document.write('<div class="lnb-bottom-cnt">');
		document.write('<div class="lnb-bnr"><a href="#"><img src="../../images/_samples/@sample_330x80.jpg" alt="7월 신상품" /></a></div>');
		document.write('');
		document.write('<div class="lnb-brand-area">');
		document.write('<div class="tit-head inner-flex">');
		document.write('<strong class="lnb-cnt-tit left-item1">브랜드관</strong>');
		document.write('<div class="right-item1"><a href="#" class="btn-link-txt3"><span>전체보기</span><i class="ico-arr-right"></i></a></div>');
		document.write('</div>');
		document.write('<div class="scroll-y-area">');
		document.write('<ul class="lnb-brand-list">');
		document.write('<li><a href="#"><img src="../../images/_samples/@sample_132x132.png" alt="맛있닭" /><span class="txt text-elps">맛있닭맛있닭맛있닭</span></a></li>');
		document.write('<li><a href="#"><img src="../../images/_samples/@sample_132x132.png" alt="맛있닭" /><span class="txt text-elps">맛있닭</span></a></li>');
		document.write('<li><a href="#"><img src="../../images/_samples/@sample_132x132.png" alt="맛있닭" /><span class="txt text-elps">맛있닭</span></a></li>');
		document.write('<li><a href="#"><img src="../../images/_samples/@sample_132x132.png" alt="맛있닭" /><span class="txt text-elps">맛있닭</span></a></li>');
		document.write('<li><a href="#"><img src="../../images/_samples/@sample_132x132.png" alt="맛있닭" /><span class="txt text-elps">맛있닭</span></a></li>');
		document.write('<li><a href="#"><img src="../../images/_samples/@sample_132x132.png" alt="맛있닭" /><span class="txt text-elps">맛있닭</span></a></li>');
		document.write('<li><a href="#"><img src="../../images/_samples/@sample_132x132.png" alt="맛있닭" /><span class="txt text-elps">맛있닭</span></a></li>');
		document.write('<li><a href="#"><img src="../../images/_samples/@sample_132x132.png" alt="맛있닭" /><span class="txt text-elps">맛있닭</span></a></li>');
		document.write('</ul>');
		document.write('</div><!--// scroll-y-area -->');
		document.write('</div><!--// lnb-brand-area -->');
		document.write('<div class="cs-call">');
		document.write('<a href="tel:02-6405-8088">고객센터 <em>02.6405.8088</em></a>');
		document.write('</div>');
		document.write('</div><!--// lnb-bottom-cnt -->');
		document.write('</div><!--// lnb-body -->');
		document.write('<button type="button" class="btn-x-md2 ui-close-lnb" title="닫기"><i class="ico-x-white"></i><span class="blind">닫기</span></button>');
		document.write('</div>');
		document.write('</div><!--// lnb-wrap -->');
	},
	bottomNav : function(){
		document.write('<div class="bottom-fixed-bar">');
		document.write('<ul class="bottom-menu">');
		document.write('<li><button type="button" data-layer="#lnb" class="ui-open-lnb"><i class="ico-cate-menu"></i><span class="blind">전체 메뉴</span></button></li>');
		document.write('<li><a href="#"><i class="ico-bottom-my"></i><span class="blind">마이랭닭</span></a></li>');
		document.write('<li><a href="#"><i class="ico-bottom-main"></i><span class="blind">메인</span></a></li>');
		document.write('<li><a href="#"><i class="ico-bottom-coupon"></i><span class="blind">쿠폰</span></a></li>');
		document.write('<li>');
		document.write('<a href="#" class="btn-recent-view">');
		document.write('<span class="blind">최근 본 상품</span>');
		document.write('<img src="../../images/_samples/@sample_200x200.png" alt="" />');
		document.write('<span class="num">3</span>');
		document.write('</a>');
		document.write('</li>');
		document.write('<!-- 최근 본 상품이 없을 경우');
		document.write('<li>');
		document.write('<a href="#" class="btn-recent-view">');
		document.write('<span class="blind">최근 본 상품</span>');
		document.write('<span class="num">0</span>');
		document.write('</a>');
		document.write('</li>');
		document.write('-->');
		document.write('</ul>');
		document.write('</div><!--// bottom-fixed-bar -->');
	},
	footer : function(){
		document.write('<footer id="footer" class="footer">');
		document.write('<ul class="footer-links">');
		document.write('<li><a href="#">로그인</a></li>');
		document.write('<li><a href="#">고객센터</a></li>');
		document.write('<li><a href="#">고객의 소리</a></li>');
		document.write('</ul>');
		document.write('<div class="footer-inner">');
		document.write('<div class="footer-cs-info">');
		document.write('<p class="cs-guide">고객센터 <i class="ico-bl-phone"></i><strong class="text-primary">02-6405-8088</strong></p>');
		document.write('<p>평일 09:00 ~ 18:00 (점심 12:00 ~ 13:00)<br />주말, 공휴일 휴무</p>');
		document.write('</div>');
		document.write('<ul class="footer-menu-list">');
		document.write('<li><a href="#">공지사항</a></li>');
		document.write('<li><a href="#">이용약관</a></li>');
		document.write('<li><a href="#"><em>개인정보처리방침</em></a></li>');
		document.write('</ul>');
		document.write('</div>');
		document.write('<div class="footer-inner">');
		document.write('<div class="ui-toggle-slide">');
		document.write('<div class="footer-toggle">');
		document.write('<button type="button" class="ui-slide-btn"><span>(주)푸드나무 사업자정보확인</span><i class="ico-arr-toggle"></i></button>');
		document.write('</div><!--// footer-toggle -->');
		document.write('<div class="hide ui-slide-content">');
		document.write('<ul class="footer-addr-info">');
		document.write('<li><p>㈜푸드나무 대표 : 김영문</p><p>개인정보보호책임자 : 김영완</p></li>');
		document.write('<li>사업자등록번호 : 105-87-81968 <a href="#" class="btn-link-txt4"><span>사업자정보확인</span><i class="ico-arr-right2"></i></a></li>');
		document.write('<li>통신판매신고 : 제2015-서울마포-1058호</li>');
		document.write('<li><address>서울특별시 마포구 월드컵북로 396, 15층<br />(상암동, 누리꿈스퀘어 비지니스</address></li>');
		document.write('</ul>');
		document.write('<dl class="footer-service-info">');
		document.write('<dt class="tit"><a href="#" class="btn-link-txt4"><span>채무지급보증안내</span><i class="ico-arr-right2"></i></a></dt>');
		document.write('<dd>당사는 고객님이 현금결제한 금액에 대해 우리은행과채무 지급보증 계약을 체결하여 안전거래를 보장하고 있습니다.</dd>');
		document.write('</dl>');
		document.write('</div><!--// ui-slide-content -->');
		document.write('</div><!--// ui-toggle-slide -->');
		document.write('<ul class="footer-sns-list">');
		document.write('<li><a href="#" title="페이스북"><i class="ico-sns-facebook"></i><span class="blind">페이스북</span></a></li>');
		document.write('<li><a href="#" title="인스타그램"><i class="ico-sns-instagram"></i><span class="blind">인스타그램</span></a></li>');
		document.write('<li><a href="#" title="네이버블로그"><i class="ico-sns-blog"></i><span class="blind">네이버블로그</span></a></li>');
		document.write('<li><a href="#" title="네이버포스트"><i class="ico-sns-post"></i><span class="blind">네이버포스트</span></a></li>');
		document.write('<li><a href="#" title="카카오톡"><i class="ico-sns-kakaotalk"></i><span class="blind">카카오톡</span></a></li>');
		document.write('<li><a href="#" title="카카오스토리"><i class="ico-sns-kakaostory"></i><span class="blind">카카오스토리</span></a></li>');
		document.write('</ul>');
		document.write('<p class="copyright">©랭킹닭컴 All rights reserved.</p>');
		document.write('</div>');
		document.write('</footer>');
	}
}