var baseURL = '../../';
var commURL = '../../../common/';
var include = {
	meta : function(){
		document.write('<meta http-equiv="X-UA-Compatible" content="IE=edge">');
		document.write('<meta name="viewport" content="width=device-width, initial-scale=1">');
		//document.write('<meta name="format-detection" content="telephone=no">');
	},
	styles : function(){
		document.write('<link rel="stylesheet" href="'+baseURL+'css/common.css" type="text/css" />');
		document.write('<link rel="stylesheet" href="'+baseURL+'css/content.css" type="text/css" />');
	},
	scripts : function(){
		document.write('<script src="'+commURL+'js/lib/jquery-3.5.1.min.js"></script>');
		document.write('<script src="'+commURL+'js/lib/swiper.js"></script>');
		document.write('<script src="'+baseURL+'js/pub/content_ui.js"></script>');
		document.write('<script src="'+commURL+'js/lib/jquery.mCustomScrollbar.concat.min.js"></script>');
	},
	title : function(){
		document.write('<title>랭킹닭컴</title>');
	},
	skipNav : function(){
		document.write('<div class="skip-navi"><a href="#gnb">주요 메뉴 바로가기</a><a href="#contents">본문 컨텐츠 바로가기</a></div>');
	},
	header : function(){
		document.write('<div class="header-inner">');
		document.write('<h1 class="logo"><a href="#"><span class="blind">랭킹닭컴</span></a></h1>');
		document.write('<div class="util">');
		document.write('<ul>');
		document.write('<li><a href="#">로그인</a></li>');
		document.write('<li><a href="#">회원가입</a></li>');
		document.write('<li><a href="#">주문조회</a></li>');
		document.write('<li><a href="#">고객센터</a></li>');
		document.write('</ul>');
		document.write('</div><!--// util -->');
		document.write('<div class="header-search">');
		document.write('<div class="top-search">');
		document.write('<input type="search" class="input-search" value="국민간식 단백천하 소시지" />');
		document.write('<button type="button" class="btn-top-search" title="검색"><span class="blind">검색</span></button>');
		document.write('</div>');
		document.write('<div class="search-layer">');
		document.write('<div class="tit-area"><h2>인기 검색어</h2></div>');
		document.write('<div class="search-rank">');
		document.write('<ol class="list">');
		document.write('<li>');
		document.write('<a href="#">');
		document.write('<em class="num">1</em><span class="word">닭가슴살 스테이크</span>');
		document.write('<span class="state text-green">NEW</span>');
		document.write('</a>');
		document.write('</li>');
		document.write('<li>');
		document.write('<a href="#">');
		document.write('<em class="num">2</em><span class="word">다이어트 도시락</span>');
		document.write('<span class="state">-</span>');
		document.write('</a>');
		document.write('</li>');
		document.write('<li>');
		document.write('<a href="#">');
		document.write('<em class="num">3</em><span class="word">핫도그</span>');
		document.write('<span class="state text-green">NEW</span>');
		document.write('</a>');
		document.write('</li>');
		document.write('<li>');
		document.write('<a href="#">');
		document.write('<em class="num">4</em><span class="word">패키지</span>');
		document.write('<span class="state text-primary"><i class="ico-arrfill-up"><span class="blind">up</span></i>4</span>');
		document.write('</a>');
		document.write('</li>');
		document.write('<li>');
		document.write('<a href="#">');
		document.write('<em class="num">5</em><span class="word">맛있닭 스팀</span>');
		document.write('<span class="state text-blue"><i class="ico-arrfill-down"><span class="blind">down</span></i>1</span>');
		document.write('</a>');
		document.write('</li>');
		document.write('</ol>');
		document.write('<ol class="list">');
		document.write('<li>');
		document.write('<a href="#">');
		document.write('<em class="num">6</em><span class="word">스파클링</span>');
		document.write('<span class="state">-</span>');
		document.write('</a>');
		document.write('</li>');
		document.write('<li>');
		document.write('<a href="#">');
		document.write('<em class="num">7</em><span class="word">잇메이트</span>');
		document.write('<span class="state text-green">NEW</span>');
		document.write('</a>');
		document.write('</li>');
		document.write('<li>');
		document.write('<a href="#">');
		document.write('<em class="num">8</em><span class="word">단백천하</span>');
		document.write('<span class="state text-green">NEW</span>');
		document.write('</a>');
		document.write('</li>');
		document.write('<li>');
		document.write('<a href="#">');
		document.write('<em class="num">9</em><span class="word">추가 증정</span>');
		document.write('<span class="state text-blue"><i class="ico-arrfill-down"><span class="blind">down</span></i>1</span>');
		document.write('</a>');
		document.write('</li>');
		document.write('<li>');
		document.write('<a href="#">');
		document.write('<em class="num">10</em><span class="word">간식</span>');
		document.write('<span class="state text-green">NEW</span>');
		document.write('</a>');
		document.write('</li>');
		document.write('</ol>');
		document.write('</div><!--// search-rank -->');
		document.write('<div class="search-bottom">');
		document.write('<div class="tit">');
		document.write('<h3>최근검색어</h3>');
		document.write('<button type="button" class="text-guide-sm"><span>전체삭제</span></button>');
		document.write('</div>');
		document.write('<div class="latest-search">');
		document.write('<!-- 검색어 있을 경우 -->');
		document.write('<ul class="srch-list">');
		document.write('<li>');
		document.write('<div class="srch-keyword">');
		document.write('<a href="#" class="txt">잇메이트</a>');
		document.write('<button type="button" class="btn-x-xs" title="삭제"><i class="ico-x-grey2"></i><span class="blind">삭제</span></button>');
		document.write('</div>');
		document.write('</li>');
		document.write('<li>');
		document.write('<div class="srch-keyword">');
		document.write('<a href="#" class="txt">단백천하</a>');
		document.write('<button type="button" class="btn-x-xs" title="삭제"><i class="ico-x-grey2"></i><span class="blind">삭제</span></button>');
		document.write('</div>');
		document.write('</li>');
		document.write('<li>');
		document.write('<div class="srch-keyword">');
		document.write('<a href="#" class="txt">스파클링</a>');
		document.write('<button type="button" class="btn-x-xs" title="삭제"><i class="ico-x-grey2"></i><span class="blind">삭제</span></button>');
		document.write('</div>');
		document.write('</li>');
		document.write('<li>');
		document.write('<div class="srch-keyword">');
		document.write('<a href="#" class="txt">맛있닭 스팀</a>');
		document.write('<button type="button" class="btn-x-xs" title="삭제"><i class="ico-x-grey2"></i><span class="blind">삭제</span></button>');
		document.write('</div>');
		document.write('</li>');
		document.write('<li>');
		document.write('<div class="srch-keyword">');
		document.write('<a href="#" class="txt">다이어트 도시락</a>');
		document.write('<button type="button" class="btn-x-xs" title="삭제"><i class="ico-x-grey2"></i><span class="blind">삭제</span></button>');
		document.write('</div>');
		document.write('</li>');
		document.write('</ul>');
		document.write('<!--// 검색어 있을 경우 -->');
		document.write('<!-- 검색어 없을 경우 ');
		document.write('<div class="no-data"><p class="message">최근 검색어가 없습니다.</p></div>');
		document.write('-->	');
		document.write('</div><!--// latest-search -->');
		document.write('</div><!--// search-bottom -->');
		document.write('</div><!--// search-layer -->');
		document.write('</div><!--// header-search -->');
		document.write('<div class="my-menu">');
		document.write('<ul>');
		document.write('<li><a href="#" class="btn-util-mypage" title="마이페이지"><span class="blind">마이페이지</span></a></li>');
		document.write('<li><a href="#" class="btn-util-cart" title="장바구니"><span class="blind">장바구니</span><em class="count">1</em></a></li>');
		document.write('</ul>');
		document.write('</div><!--// my-menu -->');
		document.write('</div><!--// header-inner -->');
		document.write('<div class="gnb-wrap">');
		document.write('<div class="inner">');
		document.write('<div class="category-wrap">');
		document.write('<a href="#all-category" class="btn-menu-all"><span>전체 카테고리</span></a>');
		document.write('<nav id="all-category" class="category-menu">');
		document.write('<ul class="cate-dep1">');
		document.write('<li><a href="#"><i class="ico-cate-gnb cate-new"></i><span class="menu">신상품</span></a></li>');
		document.write('<li>');
		document.write('<a href="#"><i class="ico-cate-gnb cate-chicken"></i><span class="menu">닭가슴살</span></a>');
		document.write('<ul class="cate-dep2">');
		document.write('<li><a href="#"><span>전체</span></a></li>');
		document.write('<li><a href="#"><span>스팀&middot;소프트</span></a></li>');
		document.write('<li><a href="#"><span>스테이크</span></a></li>');
		document.write('<li><a href="#"><span>볼&middot;큐브</span></a></li>');
		document.write('<li><a href="#"><span>슬라이스&middot;소스</span></a></li>');
		document.write('<li><a href="#"><span>훈제</span></a></li>');
		document.write('<li><a href="#"><span>프로틴</span></a></li>');
		document.write('<li><a href="#"><span>저염&middot;염분무첨가</span></a></li>');
		document.write('<li><a href="#"><span>소시지&middot;햄</span></a></li>');
		document.write('<li><a href="#"><span>소스닭가슴살</span></a></li>');
		document.write('<li><a href="#"><span>생&middot;다짐육</span></a></li>');
		document.write('<li><a href="#"><span>육포</span></a></li>');
		document.write('<li><a href="#"><span>실온 보관</span></a></li>');
		document.write('<li><a href="#"><span>스낵&middot;칩</span></a></li>');
		document.write('</ul> ');                     
		document.write('</li>');
		document.write('<li>');
		document.write('<a href="#"><i class="ico-cate-gnb cate-instant"></i><span class="menu">즉석 간편식</span></a>');
		document.write('<ul class="cate-dep2">');
		document.write('<li><a href="#"><span>전체</span></a></li>');
		document.write('<li><a href="#"><span>즉석밥</span></a></li>');
		document.write('<li><a href="#"><span>핫도그&middot;브리또</span></a></li>');
		document.write('<li><a href="#"><span>카레&middot;짜장</span></a></li>');
		document.write('<li><a href="#"><span>라면&middot;쌀국수</span></a></li>');
		document.write('<li><a href="#"><span>곤약면&middot;파스타</span></a></li>');
		document.write('<li><a href="#"><span>떡볶이&middot;튀김&middot;순대</span></a></li>');
		document.write('<li><a href="#"><span>피자&middot;치킨&middot;탕수육</span></a></li>');
		document.write('<li><a href="#"><span>만두</span></a></li>');
		document.write('</ul>  ');                    
		document.write('</li>');
		document.write('<li>');
		document.write('<a href="#"><i class="ico-cate-gnb cate-lunchbox"></i><span class="menu">도시락&middot;볶음밥</span></a>');
		document.write('<ul class="cate-dep2">');
		document.write('<li><a href="#"><span>전체</span></a></li>');
		document.write('<li><a href="#"><span>다이어트 도시락</span></a></li>');
		document.write('<li><a href="#"><span>더담은 도시락</span></a></li>');
		document.write('<li><a href="#"><span>간편 도시락</span></a></li>');
		document.write('<li><a href="#"><span>볶음밥</span></a></li>');
		document.write('<li><a href="#"><span>덮밥&middot;컵밥</span></a></li>');
		document.write('</ul>');
		document.write('</li>');
		document.write('<li>');
		document.write('<a href="#"><i class="ico-cate-gnb cate-bread"></i><span class="menu">빵&middot;시리얼&middot;간식</span></a>');
		document.write('<ul class="cate-dep2">');
		document.write('<li><a href="#"><span>전체</span></a></li>');
		document.write('<li><a href="#"><span>베이커리</span></a></li>');
		document.write('<li><a href="#"><span>과자&middot;쿠키</span></a></li>');
		document.write('<li><a href="#"><span>시리얼&middot;바</span></a></li>');
		document.write('<li><a href="#"><span>초콜릿&middot;젤리</span></a></li>');
		document.write('<li><a href="#"><span>곤약젤리</span></a></li>');
		document.write('<li><a href="#"><span>아이스크림</span></a></li>');
		document.write('</ul>');
		document.write('</li>');
		document.write('<li>');
		document.write('<a href="#"><i class="ico-cate-gnb cate-salad"></i><span class="menu">샐러드&middot;과일</span></a>');
		document.write('<ul class="cate-dep2">');
		document.write('<li><a href="#"><span>전체</span></a></li>');
		document.write('<li><a href="#"><span>알뜰샐러드</span></a></li>');
		document.write('<li><a href="#"><span>토핑샐러드</span></a></li>');
		document.write('<li><a href="#"><span>과일</span></a></li>');
		document.write('<li><a href="#"><span>드레싱</span></a></li>');
		document.write('</ul>');
		document.write('</li>');
		document.write('<li>');
		document.write('<a href="#"><i class="ico-cate-gnb cate-beverage"></i><span class="menu">음료&middot;프로틴</span></a>');
		document.write('<ul class="cate-dep2">');
		document.write('<li><a href="#"><span>전체</span></a></li>');
		document.write('<li><a href="#"><span>우유&middot;두유</span></a></li>');
		document.write('<li><a href="#"><span>물&middot;탄산수</span></a></li>');
		document.write('<li><a href="#"><span>과일&middot;건강즙</span></a></li>');
		document.write('<li><a href="#"><span>프로틴 음료</span></a></li>');
		document.write('<li><a href="#"><span>프로틴 쉐이크</span></a></li>');
		document.write('<li><a href="#"><span>커피&middot;차</span></a></li>');
		document.write('<li><a href="#"><span>클렌즈 주스</span></a></li>');
		document.write('</ul>');
		document.write('</li>');
		document.write('<li>');
		document.write('<a href="#"><i class="ico-cate-gnb cate-meat"></i><span class="menu">육류&middot;달걀&middot;콩</span></a>');
		document.write('<ul class="cate-dep2">');
		document.write('<li><a href="#"><span>전체</span></a></li>');
		document.write('<li><a href="#"><span>돼지고기</span></a></li>');
		document.write('<li><a href="#"><span>소고기</span></a></li>');
		document.write('<li><a href="#"><span>닭&middot;오리고기</span></a></li>');
		document.write('<li><a href="#"><span>구운&middot;훈제&middot;반숙란</span></a></li>');
		document.write('<li><a href="#"><span>계란흰자</span></a></li>');
		document.write('<li><a href="#"><span>콩&middot;비건</span></a></li>');
		document.write('</ul>');
		document.write('</li>');
		document.write('<li>');
		document.write('<a href="#"><i class="ico-cate-gnb cate-nuts"></i><span class="menu">견과&middot;고구마&middot;감자</span></a>');
		document.write('<ul class="cate-dep2">');
		document.write('<li><a href="#"><span>전체</span></a></li>');
		document.write('<li><a href="#"><span>견과</span></a></li>');
		document.write('<li><a href="#"><span>고구마</span></a></li>');
		document.write('<li><a href="#"><span>감자</span></a></li>');
		document.write('<li><a href="#"><span>호박</span></a></li>');
		document.write('<li><a href="#"><span>밤</span></a></li>');
		document.write('</ul>');
		document.write('</li>');
		document.write('<li>');
		document.write('<a href="#"><i class="ico-cate-gnb cate-sidedish"></i><span class="menu">반찬&middot;밀키트&middot;안주</span></a>');
		document.write('<ul class="cate-dep2">');
		document.write('<li><a href="#"><span>전체</span></a></li>');
		document.write('<li><a href="#"><span>밀키트</span></a></li>');
		document.write('<li><a href="#"><span>햄&middot;소시지</span></a></li>');
		document.write('<li><a href="#"><span>잡채&middot;동그랑땡</span></a></li>');
		document.write('<li><a href="#"><span>건강반찬</span></a></li>');
		document.write('<li><a href="#"><span>국&middot;탕&middot;찌개</span></a></li>');
		document.write('<li><a href="#"><span>건강 안주</span></a></li>');
		document.write('<li><a href="#"><span>곱창&middot;껍데기</span></a></li>');
		document.write('</ul>');
		document.write('</li>');
		document.write('<li>');
		document.write('<a href="#"><i class="ico-cate-gnb cate-health"></i><span class="menu">건강식품</span></a>');
		document.write('<ul class="cate-dep2">');
		document.write('<li><a href="#"><span>전체</span></a></li>');
		document.write('<li><a href="#"><span>영양제&middot;비타민</span></a></li>');
		document.write('<li><a href="#"><span>흑마늘&middot;꿀&middot;홍삼</span></a></li>');
		document.write('<li><a href="#"><span>다이어트 보조제</span></a></li>');
		document.write('<li><a href="#"><span>콜라겐</span></a></li>');
		document.write('</ul>');
		document.write('</li>');
		document.write('<li>');
		document.write('<a href="#"><i class="ico-cate-gnb cate-seafood"></i><span class="menu">수산&middot;해산</span></a>');
		document.write('<ul class="cate-dep2">');
		document.write('<li><a href="#"><span>전체</span></a></li>');
		document.write('<li><a href="#"><span>생선구이</span></a></li>');
		document.write('<li><a href="#"><span>연어&middot;참치</span></a></li>');
		document.write('<li><a href="#"><span>오징어</span></a></li>');
		document.write('<li><a href="#"><span>어묵&middot;스테이크</span></a></li>');
		document.write('<li><a href="#"><span>다시마&middot;해조류</span></a></li>');
		document.write('<li><a href="#"><span>황태포&middot;쥐포</span></a></li>');
		document.write('</ul>');
		document.write('</li>');
		document.write('<li>');
		document.write('<a href="#"><i class="ico-cate-gnb cate-sauce"></i><span class="menu">소스&middot;잼&middot;오일</span></a>');
		document.write('<ul class="cate-dep2">');
		document.write('<li><a href="#"><span>전체</span></a></li>');
		document.write('<li><a href="#"><span>소스&middot;드레싱</span></a></li>');
		document.write('<li><a href="#"><span>과일청</span></a></li>');
		document.write('<li><a href="#"><span>잼</span></a></li>');
		document.write('<li><a href="#"><span>분말&middot;오일</span></a></li>');
		document.write('</ul>');
		document.write('</li>');
		document.write('<li>');
		document.write('<a href="#"><i class="ico-cate-gnb cate-set"></i><span class="menu">세트&middot;패키지</span></a>');
		document.write('<ul class="cate-dep2">');
		document.write('<li><a href="#"><span>전체</span></a></li>');
		document.write('<li><a href="#"><span>식단</span></a></li>');
		document.write('<li><a href="#"><span>맛보기</span></a></li>');
		document.write('<li><a href="#"><span>선물세트</span></a></li>');
		document.write('</ul>');
		document.write('</li>');
		document.write('<li>');
		document.write('<a href="#"><i class="ico-cate-gnb cate-exer"></i><span class="menu">운동용품</span></a>');
		document.write('<ul class="cate-dep2">');
		document.write('<li><a href="#"><span>전체</span></a></li>');
		document.write('<li><a href="#"><span>스트랩&middot;장갑</span></a></li>');
		document.write('<li><a href="#"><span>보호대&middot;밴드</span></a></li>');
		document.write('<li><a href="#"><span>보틀&middot;쉐이커</span></a></li>');
		document.write('<li><a href="#"><span>홈트레이닝</span></a></li>');
		document.write('<li><a href="#"><span>스포츠웨어</span></a></li>');
		document.write('<li><a href="#"><span>굿즈</span></a></li>');
		document.write('</ul>');
		document.write('</li>');
		document.write('</ul>');
		document.write('</nav><!--// category-menu -->');
		document.write('</div><!--// category-wrap -->');
		document.write('<nav id="gnb" class="gnb">');
		document.write('<ul>');
		document.write('<li><a href="#"><span>랭킹</span></a></li>');
		document.write('<li><a href="#"><span>혜택정리</span></a></li>');
		document.write('<li><a href="#"><span>브랜드관</span></a></li>');
		document.write('<li><a href="#"><span>이달의 특가</span></a></li>');
		document.write('<li><a href="#"><span>1팩 담기</span></a></li>');
		document.write('<li><a href="#"><span>이벤트 &middot; 후기</span></a></li>');
		document.write('<li><a href="#"><em class="ico-txt-gnb"><span class="blind">특급배송</span></em></a></li>');
		document.write('</ul>');
		document.write('</nav><!--// gnb -->');
		document.write('</div><!--// inner -->');
		document.write('</div><!--// gnb-wrap -->');
	},
	sidequick : function(){
		document.write('<div class="side-quick-area">');
		document.write('<div class="side-quick">');
		document.write('<ul class="bnrs">');
		document.write('<li><a href="#"><img src="../../images/_samples/@sample_100x153.png" alt="랭킹 상사 - 바로가기" /></a></li>');
		document.write('<li><a href="#"><img src="../../images/_samples/@sample_100x187.png" alt="맛있닭 맛보기 set - 구매하러 가기" /></a></li>');
		document.write('</ul><!--// bnrs -->');
		document.write('<div class="recent-list">');
		document.write('<div class="recent-info"><p class="txt">최근 본 <span class="num"><em>0</em><i class="ico-arr-right"></i></span></p></div>');
		document.write('<!-- 상품 목록 영역 -->');
		document.write('<div class="recent-prd-item">');
		document.write('<ul>');
		document.write('<li>');
		document.write('<a href="#">');
		document.write('<span class="img"><img src="../../images/_samples/@sample_74x74.jpg" alt="최근 본 상품" /></span>');
		document.write('<div class="detail">');
		document.write('<span class="tit text-elps">맛있닭 맛보기 set - 구매하러 가기 맛있닭 맛보기 set - 구매하러 가기</span>');
		document.write('<span class="text-primary">19,800</span>');
		document.write('</div>');
		document.write('</a>');
		document.write('</li>');
		document.write('<li>');
		document.write('<a href="#">');
		document.write('<span class="img"><img src="../../images/_samples/@sample_74x74.jpg" alt="최근 본 상품" /></span>');
		document.write('<div class="detail">');
		document.write('<span class="tit text-elps">맛있닭 맛보기 set - 구매하러 가기 맛있닭 맛보기 set - 구매하러 가기</span>');
		document.write('<span class="text-primary">19,800</span>');
		document.write('</div>');
		document.write('</a>');
		document.write('</li>');
		document.write('<li>');
		document.write('<a href="#">');
		document.write('<span class="img"><img src="../../images/_samples/@sample_74x74.jpg" alt="최근 본 상품" /></span>');
		document.write('<div class="detail">');
		document.write('<span class="tit text-elps">맛있닭 맛보기 set - 구매하러 가기 맛있닭 맛보기 set - 구매하러 가기</span>');
		document.write('<span class="text-primary">19,800</span>');
		document.write('</div>');
		document.write('</a>');
		document.write('</li>');
		document.write('<li>');
		document.write('<a href="#">');
		document.write('<span class="img"><img src="../../images/_samples/@sample_74x74.jpg" alt="최근 본 상품" /></span>');
		document.write('<div class="detail">');
		document.write('<span class="tit text-elps">맛있닭 맛보기 set - 구매하러 가기 맛있닭 맛보기 set - 구매하러 가기</span>');
		document.write('<span class="text-primary">19,800</span>');
		document.write('</div>');
		document.write('</a>');
		document.write('</li>');
		document.write('<li>');
		document.write('<a href="#">');
		document.write('<span class="img"><img src="../../images/_samples/@sample_74x74.jpg" alt="최근 본 상품" /></span>');
		document.write('<div class="detail">');
		document.write('<span class="tit text-elps">맛있닭 맛보기 set - 구매하러 가기 맛있닭 맛보기 set - 구매하러 가기</span>');
		document.write('<span class="text-primary">19,800</span>');
		document.write('</div>');
		document.write('</a>');
		document.write('</li>');
		document.write('<li>');
		document.write('<a href="#">');
		document.write('<span class="img"><img src="../../images/_samples/@sample_74x74.jpg" alt="최근 본 상품" /></span>');
		document.write('<div class="detail">');
		document.write('<span class="tit text-elps">맛있닭 맛보기 set - 구매하러 가기 맛있닭 맛보기 set - 구매하러 가기</span>');
		document.write('<span class="text-primary">19,800</span>');
		document.write('</div>');
		document.write('</a>');
		document.write('</li>');
		document.write('<li>');
		document.write('<a href="#">');
		document.write('<span class="img"><img src="../../images/_samples/@sample_74x74.jpg" alt="최근 본 상품" /></span>');
		document.write('<div class="detail">');
		document.write('<span class="tit text-elps">맛있닭 맛보기 set - 구매하러 가기 맛있닭 맛보기 set - 구매하러 가기</span>');
		document.write('<span class="text-primary">19,800</span>');
		document.write('</div>');
		document.write('</a>');
		document.write('</li>');
		document.write('</ul>');
		document.write('<div class="btn-move-group">');
		document.write('<button type="button" class="btn-left-xs disabled"><i class="ico-arr-left"></i><span class="blind">이전</span></button>');
		document.write('<button type="button" class="btn-right-xs"><i class="ico-arr-right"></i><span class="blind">다음</span></button>');
		document.write('</div>');
		document.write('</div>');
		document.write('<!--// 상품 목록 영역 -->');
		document.write('<!-- 상품 없을 경우 -->');
		document.write('<!-- <div class="no-recent">');
		document.write('<div class="info-message">최근 본<br />상품 정보가<br />없습니다</div>');
		document.write('<div class="compare-message">2개 이상부터<br />상품비교가<br />가능합니다</div>');
		document.write('</div> -->');
		document.write('<!--// 상품 없을 경우 -->');
		document.write('<a href="#" class="sidebnr-link"><span>찜한 상품</span></a>');
		document.write('<a href="#" class="sidebnr-link"><span>장바구니</span></a>');
		document.write('</div><!--// recent-list -->');
		document.write('<div class="side-btns">');
		document.write('<button type="button" class="btn-side-func back" title="뒤로가기"><span class="blind">뒤로가기</span></button>');
		document.write('<button type="button" class="btn-side-func up" title="위로" onclick="goTop()"><span class="blind">위로</span></button>');
		document.write('<button type="button" class="btn-side-func down" title="아래로" onclick="goBottom()"><span class="blind">아래로</span></button>');
		document.write('</div>');
		document.write('</div><!--// side-quick -->');
		document.write('</div>');
	},
	footer : function(){
		document.write('<footer id="footer" class="footer">');
		document.write('<div class="footer-menu">');
		document.write('<div class="frame-sm">');
		document.write('<ul class="footer-menu-list">');
		document.write('<li><a href="#">회사소개</a></li>');
		document.write('<li><a href="#">공지사항</a></li>');
		document.write('<li><a href="#">입점 &middot; 제휴문의</a></li>');
		document.write('<li><a href="#">이용약관</a></li>');
		document.write('<li><a href="#" class="text-black2 text-md">개인정보처리방침</a></li>');
		document.write('</ul><!--// footer-menu-list -->');
		document.write('<div class="family-select">');
		document.write('<button type="button" class="select-btn ui-togglelayer-btn"><span>패밀리사이트</span><i class="ico-arr-toggle"></i></button>');
		document.write('<div class="family-list-box ui-togglelayer-box">');
		document.write('<ul>');
		document.write('<li><a href="https://rankingdak.com/" target="_blank"><span>랭킹닭컴</span></a></li>');
		document.write('<li><a href="https://www.ggjmart.com/" target="_blank"><span>개근질마트</span></a></li>');
		document.write('<li><a href="https://www.ggjil.com/" target="_blank"><span>개근질닷컴</span></a></li>');
		document.write('<li><a href="https://pickydiet.co.kr/" target="_blank"><span>피키다이어트</span></a></li>');
		document.write('<li><a href="http://dacook.co.kr/" target="_blank"><span>다이어트전문 레시피 닭쿡</span></a></li>');
		document.write('<li><a href="http://www.studiou.co.kr/" target="_blank"><span>바디프로필 전문 스튜디오U</span></a></li>');
		document.write('</ul>');
		document.write('</div>');
		document.write('</div><!--// family-select -->');
		document.write('</div><!--// footer-info-list -->');
		document.write('</div><!--// frame-sm -->');
		document.write('<div class="footer-info">');
		document.write('<strong class="footer-logo"><span class="blind">랭킹닭컴</span></strong>');
		document.write('<div class="colum-info">');
		document.write('<h5 class="blind">회사 정보</h5>');
		document.write('<ul class="footer-biz-info">');
		document.write('<li><span class="company-name">(주)푸드나무</span></li>');
		document.write('<li>대표 : 김영문</li>');
		document.write('<li>주소 : 서울특별시 마포구 월드컵북로 396, 15층(상암동, 누리꿈스퀘어 비지니스타워)</li>');
		document.write('<li>사업자등록번호 : 105-87-81968 사업자정보 확인</li>');
		document.write('<li>통신판매업신고번호 : 제2015-서울마포-1058호</li>');
		document.write('<li>개인정보보호책임자 : 박상필</li>');
		document.write('</ul>');
		document.write('<p class="copyright">Copyright©랭킹닭컴 All rights reserved.</p>');
		document.write('</div><!--// colum -->');
		document.write('<div class="colum-info">');
		document.write('<ul class="customer-info">');
		document.write('<li class="cscenter">고객센터 <em class="footer-tel">02-6405-8088</em></li>');
		document.write('<li>FAX. 02-6351-8088</li>');
		document.write('<li>E-mail. admin@foodnamoo.com</li>');
		document.write('</ul>');
		document.write('<div class="customer-btns">');
		document.write('<a href="#"><span>고객의소리</span></a>');
		document.write('<a href="#"><span>1:1문의</span></a>');
		document.write('</div>');
		document.write('<ul class="footer-sns-list">');
		document.write('<li><a href="https://www.facebook.com/rankingdakcom" title="페이스북" target="_blank"><i class="ico-sns-facebook"></i><span class="blind">페이스북</span></a></li>');
		document.write('<li><a href="https://www.instagram.com/rankingdak/" title="인스타그램" target="_blank"><i class="ico-sns-instagram"></i><span class="blind">인스타그램</span></a></li>');
		document.write('<li><a href="https://blog.naver.com/rankingdak" title="네이버블로그" target="_blank"><i class="ico-sns-blog"></i><span class="blind">네이버블로그</span></a></li>');
		document.write('<li><a href="https://post.naver.com/my.nhn?memberNo=9267177" title="네이버포스트" target="_blank"><i class="ico-sns-post"></i><span class="blind">네이버포스트</span></a></li>');
		document.write('<li><a href="https://pf.kakao.com/_ltFRl" title="카카오톡" target="_blank"><i class="ico-sns-kakaotalk"></i><span class="blind">카카오톡</span></a></li>');
		document.write('</ul>');
		document.write('</div><!--// colum -->');
		document.write('</div><!--// footer-info -->');
		document.write('<div class="footer-bottom">');
		document.write('<ul class="service-txt">');
		document.write('<li><a href="#"><i class="ico-footer-service01"></i>정보보호 관리체계 ISMS 인증 획득</a></li>');
		document.write('<li><a href="#"><i class="ico-footer-service02"></i>우리은행 구매 안전 서비스 가입사실 확인</a></li>');
		document.write('</ul>');
		document.write('</div>');
		document.write('</footer>');
	}
}